
/* 资源管理 --- 列表数据 */
export function resinfoList () {
  return {
    url: '/sys/resinfo/queryListByParentId',
    type: 'get',
    data: {
      "msg": "success",
      "code": 0,
      "list": [{
        "resId": 1,
        "resName": "首页",
        "resType": null,
        "icon": null,
        "resTypeDesc": null,
        "url": "index",
        "parentId": null,
        "parentName": null,
        "sortNo": 0,
        "children": null,
        "valid": false,
        "leaf": true
      }, {
        "resId": 2,
        "resName": "设备监测",
        "resType": null,
        "icon": null,
        "resTypeDesc": null,
        "url": null,
        "parentId": null,
        "parentName": null,
        "sortNo": 1,
        "children": null,
        "valid": false,
        "leaf": false
      }, {
        "resId": 11,
        "resName": "电网互动",
        "resType": null,
        "icon": null,
        "resTypeDesc": null,
        "url": null,
        "parentId": null,
        "parentName": null,
        "sortNo": 2,
        "children": null,
        "valid": false,
        "leaf": false
      }, {
        "resId": 15,
        "resName": "统计分析",
        "resType": null,
        "icon": null,
        "resTypeDesc": null,
        "url": null,
        "parentId": null,
        "parentName": null,
        "sortNo": 3,
        "children": null,
        "valid": false,
        "leaf": false
      }, {
        "resId": 17,
        "resName": "系统管理",
        "resType": null,
        "icon": null,
        "resTypeDesc": null,
        "url": null,
        "parentId": null,
        "parentName": null,
        "sortNo": 4,
        "children": null,
        "valid": false,
        "leaf": false
      }, {
        "resId": 51,
        "resName": "告警统计",
        "resType": null,
        "icon": null,
        "resTypeDesc": null,
        "url": null,
        "parentId": null,
        "parentName": null,
        "sortNo": 5,
        "children": null,
        "valid": false,
        "leaf": false
      }]
    }
  }
}

/* 菜单管理 --- 列表数据 */
export function menuList () {
  return {
    url: '/sys/menu/queryListByParentId',
    type: 'get',
    data: {
      "msg": "success",
      "code": 0,
      "list": [{
        "menuId": "1",
        "roleId": "1",
        "roleName": "admin",
        "resId": 1,
        "resName": "首页",
        "name": "首页",
        "icon": "icon-home",
        "parentId": "-1",
        "parentName": null,
        "sortNo": 1,
        "children": null,
        "open": null,
        "list": null,
        "url": null,
        "type": null,
        "leaf": false
      }, {
        "menuId": "2",
        "roleId": "1",
        "roleName": "admin",
        "resId": 2,
        "resName": "设备监测",
        "name": "设备监测",
        "icon": "icon-display",
        "parentId": "-1",
        "parentName": null,
        "sortNo": 1,
        "children": null,
        "open": null,
        "list": null,
        "url": null,
        "type": null,
        "leaf": false
      }, {
        "menuId": "11",
        "roleId": "1",
        "roleName": "admin",
        "resId": 11,
        "resName": "电网互动",
        "name": "电网互动",
        "icon": "icon-stats-dots",
        "parentId": "-1",
        "parentName": null,
        "sortNo": 2,
        "children": null,
        "open": null,
        "list": null,
        "url": null,
        "type": null,
        "leaf": false
      }, {
        "menuId": "15",
        "roleId": "1",
        "roleName": "admin",
        "resId": 15,
        "resName": "统计分析",
        "name": "统计分析",
        "icon": "icon-pie-chart",
        "parentId": "-1",
        "parentName": null,
        "sortNo": 3,
        "children": null,
        "open": null,
        "list": null,
        "url": null,
        "type": null,
        "leaf": false
      }, {
        "menuId": "17",
        "roleId": "1",
        "roleName": "admin",
        "resId": 17,
        "resName": "系统管理",
        "name": "系统管理",
        "icon": "icon-setting",
        "parentId": "-1",
        "parentName": null,
        "sortNo": 4,
        "children": null,
        "open": null,
        "list": null,
        "url": null,
        "type": null,
        "leaf": false
      }, {
        "menuId": "51",
        "roleId": "1",
        "roleName": "admin",
        "resId": 51,
        "resName": "告警统计",
        "name": "告警统计",
        "icon": "icon-warning-chart",
        "parentId": "-1",
        "parentName": null,
        "sortNo": 6,
        "children": null,
        "open": null,
        "list": null,
        "url": null,
        "type": null,
        "leaf": false
      }]
    }
  }
}


/* 用户管理 --- 列表数据 */
export function userList () {
  return {
    url: '/sys/user/list',
    type: 'get',
    data: {
      "msg": "success",
      "code": 0,
      "page": {
        "totalCount": 9,
        "pageSize": 10,
        "totalPage": 1,
        "currPage": 1,
        "list": [{
          "userId": "1",
          "roleId": "1",
          "roleName": "admin",
          "userName": "admin",
          "tel": "1",
          "sex": 1,
          "idCard": "1",
          "email": "1",
          "wechatId": "1",
          "orgId": "-100",
          "orgName": "平台组织机构",
          "deptId": "9ddcda4aa38447bfac2fd461819c52e0",
          "deptName": null,
          "registTime": "2018-02-03 04:12:12",
          "expiryDate": null,
          "busObjType": 1,
          "busObjsDesc": "充电桩,配电,照明,插座,空调,锅炉,热泵,光伏,储能,给水,燃气",
          "optAuth": 1,
          "optAuthDesc": "控,删,改,增,查",
          "person": false,
          "sys": true
        }, {
          "userId": "33724320ceab4d18bf3d5e4c7718adf4",
          "roleId": "1",
          "roleName": "admin",
          "userName": "test",
          "tel": "15326325632",
          "sex": null,
          "idCard": null,
          "email": null,
          "wechatId": null,
          "orgId": "-100",
          "orgName": "平台组织机构",
          "deptId": "9ddcda4aa38447bfac2fd461819c52e0",
          "deptName": null,
          "registTime": "2019-01-25 19:41:56",
          "expiryDate": null,
          "busObjType": 2047,
          "busObjsDesc": "充电桩,配电,照明,插座,空调,锅炉,热泵,光伏,储能,给水,燃气",
          "optAuth": 31,
          "optAuthDesc": "控,删,改,增,查",
          "person": false,
          "sys": false
        }, {
          "userId": "4a39176c4d0b4aa4b661344a84958860",
          "roleId": "1",
          "roleName": "admin",
          "userName": "test",
          "tel": "18326955343",
          "sex": null,
          "idCard": null,
          "email": null,
          "wechatId": null,
          "orgId": "-100",
          "orgName": "平台组织机构",
          "deptId": "9ddcda4aa38447bfac2fd461819c52e0",
          "deptName": null,
          "registTime": "2019-02-21 19:15:28",
          "expiryDate": null,
          "busObjType": 257,
          "busObjsDesc": "充电桩,配电,照明,插座,空调,锅炉,热泵,光伏,储能,给水,燃气",
          "optAuth": 3,
          "optAuthDesc": "控,删,改,增,查",
          "person": false,
          "sys": true
        }, {
          "userId": "5710c3cd74da49f5b4d67db526709908",
          "roleId": "1",
          "roleName": "admin",
          "userName": "123",
          "tel": "12345678987",
          "sex": null,
          "idCard": null,
          "email": null,
          "wechatId": null,
          "orgId": "-100",
          "orgName": "平台组织机构",
          "deptId": "9ddcda4aa38447bfac2fd461819c52e0",
          "deptName": null,
          "registTime": "2019-01-30 11:17:21",
          "expiryDate": null,
          "busObjType": 257,
          "busObjsDesc": "充电桩,配电,照明,插座,空调,锅炉,热泵,光伏,储能,给水,燃气",
          "optAuth": 1,
          "optAuthDesc": "控,删,改,增,查",
          "person": false,
          "sys": true
        }, {
          "userId": "5897a899891b422f9986291492726ede",
          "roleId": "1",
          "roleName": "admin",
          "userName": "dyf",
          "tel": "13811111111",
          "sex": null,
          "idCard": null,
          "email": null,
          "wechatId": null,
          "orgId": "-100",
          "orgName": "平台组织机构",
          "deptId": "9ddcda4aa38447bfac2fd461819c52e0",
          "deptName": null,
          "registTime": "2019-02-14 13:36:52",
          "expiryDate": null,
          "busObjType": 2047,
          "busObjsDesc": "充电桩,配电,照明,插座,空调,锅炉,热泵,光伏,储能,给水,燃气",
          "optAuth": 31,
          "optAuthDesc": "控,删,改,增,查",
          "person": false,
          "sys": true
        }, {
          "userId": "591fcedfa15e4e11a4fdd89d88ebd648",
          "roleId": "1",
          "roleName": "admin",
          "userName": "sss",
          "tel": "12345678909",
          "sex": null,
          "idCard": null,
          "email": null,
          "wechatId": null,
          "orgId": "-100",
          "orgName": "平台组织机构",
          "deptId": "9ddcda4aa38447bfac2fd461819c52e0",
          "deptName": null,
          "registTime": "2019-01-29 17:00:18",
          "expiryDate": null,
          "busObjType": 256,
          "busObjsDesc": "充电桩,配电,照明,插座,空调,锅炉,热泵,光伏,储能,给水,燃气",
          "optAuth": 1,
          "optAuthDesc": "控,删,改,增,查",
          "person": false,
          "sys": true
        }, {
          "userId": "a9f61b1c3b9e4c0ab7cae3327416c063",
          "roleId": "1",
          "roleName": "admin",
          "userName": "sdsd",
          "tel": "15363636363",
          "sex": null,
          "idCard": null,
          "email": null,
          "wechatId": null,
          "orgId": "-100",
          "orgName": "平台组织机构",
          "deptId": "9ddcda4aa38447bfac2fd461819c52e0",
          "deptName": null,
          "registTime": "2019-03-01 15:31:42",
          "expiryDate": null,
          "busObjType": 1,
          "busObjsDesc": "充电桩,配电,照明,插座,空调,锅炉,热泵,光伏,储能,给水,燃气",
          "optAuth": 1,
          "optAuthDesc": "控,删,改,增,查",
          "person": false,
          "sys": false
        }, {
          "userId": "c6318c873b6e41df9036b34119843b57",
          "roleId": "1",
          "roleName": "admin",
          "userName": "pmstt",
          "tel": "13333333333",
          "sex": null,
          "idCard": null,
          "email": null,
          "wechatId": null,
          "orgId": "-100",
          "orgName": "平台组织机构",
          "deptId": "9ddcda4aa38447bfac2fd461819c52e0",
          "deptName": null,
          "registTime": "2019-02-18 13:53:50",
          "expiryDate": null,
          "busObjType": 12,
          "busObjsDesc": "充电桩,配电,照明,插座,空调,锅炉,热泵,光伏,储能,给水,燃气",
          "optAuth": 31,
          "optAuthDesc": "控,删,改,增,查",
          "person": false,
          "sys": true
        }, {
          "userId": "d8f63b7d2f084fd79291aebaae0c560a",
          "roleId": "1",
          "roleName": "admin",
          "userName": "测试",
          "tel": "15362532589",
          "sex": null,
          "idCard": null,
          "email": null,
          "wechatId": null,
          "orgId": "-100",
          "orgName": "平台组织机构",
          "deptId": "9ddcda4aa38447bfac2fd461819c52e0",
          "deptName": null,
          "registTime": "2019-01-30 11:20:42",
          "expiryDate": null,
          "busObjType": 257,
          "busObjsDesc": "充电桩,配电,照明,插座,空调,锅炉,热泵,光伏,储能,给水,燃气",
          "optAuth": 25,
          "optAuthDesc": "控,删,改,增,查",
          "person": false,
          "sys": true
        }]
      },
      "optAuth": [{
        "codeId": "10400005",
        "codeType": 1040,
        "typeName": "用户操作权限",
        "code": 16,
        "codeName": "控",
        "subCodeType": null,
        "parentId": null,
        "sortNo": 5,
        "remark": null,
        "leaf": null
      }, {
        "codeId": "10400004",
        "codeType": 1040,
        "typeName": "用户操作权限",
        "code": 8,
        "codeName": "删",
        "subCodeType": null,
        "parentId": null,
        "sortNo": 4,
        "remark": null,
        "leaf": null
      }, {
        "codeId": "10400003",
        "codeType": 1040,
        "typeName": "用户操作权限",
        "code": 4,
        "codeName": "改",
        "subCodeType": null,
        "parentId": null,
        "sortNo": 3,
        "remark": null,
        "leaf": null
      }, {
        "codeId": "10400002",
        "codeType": 1040,
        "typeName": "用户操作权限",
        "code": 2,
        "codeName": "增",
        "subCodeType": null,
        "parentId": null,
        "sortNo": 2,
        "remark": null,
        "leaf": null
      }, {
        "codeId": "10400001",
        "codeType": 1040,
        "typeName": "用户操作权限",
        "code": 1,
        "codeName": "查",
        "subCodeType": null,
        "parentId": null,
        "sortNo": 1,
        "remark": null,
        "leaf": null
      }]
    }
  }
}

/* 角色管理 --- 列表数据 */
export function roleinfoList () {
  return {
    url: '/sys/roleinfo/list',
    type: 'get',
    data: {
      "msg": "success",
      "code": 0,
      "page": {
        "totalCount": 17,
        "pageSize": 2000,
        "totalPage": 1,
        "currPage": 1,
        "list": [{
          "roleId": "d94d3db9fe664849a12d226e5688c296",
          "roleName": "123",
          "roleType": null,
          "roleTypeDesc": null,
          "orgId": "-100",
          "orgName": "平台组织机构",
          "sortNo": 1,
          "parentSoleId": null,
          "leaf": null
        }, {
          "roleId": "1",
          "roleName": "admin",
          "roleType": 1,
          "roleTypeDesc": null,
          "orgId": "-100",
          "orgName": "平台组织机构",
          "sortNo": 1,
          "parentSoleId": "1",
          "leaf": true
        }, {
          "roleId": "b99377a1df3348cfa29cab662069d77a",
          "roleName": "管理员",
          "roleType": null,
          "roleTypeDesc": null,
          "orgId": "3201030001",
          "orgName": "南京师范大学",
          "sortNo": 1,
          "parentSoleId": null,
          "leaf": null
        }, {
          "roleId": "61f86df406474fcf8fca869a2863e82a",
          "roleName": "wanziliang",
          "roleType": null,
          "roleTypeDesc": null,
          "orgId": "-100",
          "orgName": "平台组织机构",
          "sortNo": 2,
          "parentSoleId": null,
          "leaf": null
        }, {
          "roleId": "39a27ea663f749a9b6402e22fab2a755",
          "roleName": "123",
          "roleType": null,
          "roleTypeDesc": null,
          "orgId": "-100",
          "orgName": "平台组织机构",
          "sortNo": 2,
          "parentSoleId": null,
          "leaf": null
        }, {
          "roleId": "0e37a0f2009b43258a82a1a93f901102",
          "roleName": "aaa",
          "roleType": null,
          "roleTypeDesc": null,
          "orgId": "-100",
          "orgName": "平台组织机构",
          "sortNo": 2,
          "parentSoleId": null,
          "leaf": null
        }, {
          "roleId": "1988f83239fe4ecf9c55ce2d3adf7331",
          "roleName": "bbb",
          "roleType": null,
          "roleTypeDesc": null,
          "orgId": "-100",
          "orgName": "平台组织机构",
          "sortNo": 3,
          "parentSoleId": null,
          "leaf": null
        }, {
          "roleId": "c2bddf673db8470d82b78e7f9939bb57",
          "roleName": "777",
          "roleType": null,
          "roleTypeDesc": null,
          "orgId": "-100",
          "orgName": "平台组织机构",
          "sortNo": 3,
          "parentSoleId": "1",
          "leaf": null
        }, {
          "roleId": "dcc54e16a87c449f9db0a237af9a76a3",
          "roleName": "4566666",
          "roleType": null,
          "roleTypeDesc": null,
          "orgId": "-100",
          "orgName": "平台组织机构",
          "sortNo": 4,
          "parentSoleId": "1988f83239fe4ecf9c55ce2d3adf7331",
          "leaf": null
        }, {
          "roleId": "f591827b3a504e878fe178fc0685a17e",
          "roleName": "dsaf",
          "roleType": null,
          "roleTypeDesc": null,
          "orgId": "-100",
          "orgName": "平台组织机构",
          "sortNo": 4,
          "parentSoleId": null,
          "leaf": null
        }, {
          "roleId": "da377e1c39ea486aa2020dd07c24fb68",
          "roleName": "sdafadsf",
          "roleType": null,
          "roleTypeDesc": null,
          "orgId": "-100",
          "orgName": "平台组织机构",
          "sortNo": 5,
          "parentSoleId": null,
          "leaf": null
        }, {
          "roleId": "fdd573bed4104d76bf40f0486e9713d7",
          "roleName": "adsfadsf",
          "roleType": null,
          "roleTypeDesc": null,
          "orgId": "-100",
          "orgName": "平台组织机构",
          "sortNo": 6,
          "parentSoleId": null,
          "leaf": null
        }, {
          "roleId": "ebe8e43929174b0cbd22686c9f59c249",
          "roleName": "ffffff",
          "roleType": null,
          "roleTypeDesc": null,
          "orgId": "-100",
          "orgName": "平台组织机构",
          "sortNo": 7,
          "parentSoleId": null,
          "leaf": null
        }, {
          "roleId": "c7f11667328d4afe82ce1d0db55e7f10",
          "roleName": "bbb",
          "roleType": null,
          "roleTypeDesc": null,
          "orgId": "-100",
          "orgName": "平台组织机构",
          "sortNo": 8,
          "parentSoleId": null,
          "leaf": null
        }, {
          "roleId": "62b5b608edbe416d940d27761fc8b08f",
          "roleName": "22",
          "roleType": null,
          "roleTypeDesc": null,
          "orgId": "-100",
          "orgName": "平台组织机构",
          "sortNo": 10,
          "parentSoleId": null,
          "leaf": null
        }, {
          "roleId": "2d206da117ed4254b78cd8035a069514",
          "roleName": "阿斯蒂芬",
          "roleType": null,
          "roleTypeDesc": null,
          "orgId": "-100",
          "orgName": "平台组织机构",
          "sortNo": 11,
          "parentSoleId": null,
          "leaf": null
        }, {
          "roleId": "45778f95f9834e21811e6050df264819",
          "roleName": "222",
          "roleType": null,
          "roleTypeDesc": null,
          "orgId": "-100",
          "orgName": "平台组织机构",
          "sortNo": 21,
          "parentSoleId": null,
          "leaf": null
        }]
      }
    }
  }
}

/* 部门管理 --- 列表数据 */
export function deptinfoList () {
  return {
    url: '/sys/deptinfo/list',
    type: 'get',
    data: {
      "msg": "success",
      "code": 0,
      "page": {
        "totalCount": 6,
        "pageSize": 10,
        "totalPage": 1,
        "currPage": 1,
        "list": [{
          "deptId": "b4c4eb8114ab45849d1910c9f2776fbb",
          "orgId": "-100",
          "orgName": "平台组织机构",
          "deptName": "11",
          "sortNo": 3
        }, {
          "deptId": "fe51f9b1b7614e058c0ceecd3857e7ee",
          "orgId": "-100",
          "orgName": "平台组织机构",
          "deptName": "12",
          "sortNo": 4
        }, {
          "deptId": "7a3a8e38b61547b5ba8d01e849fe96c1",
          "orgId": "-100",
          "orgName": "平台组织机构",
          "deptName": "13",
          "sortNo": 5
        }, {
          "deptId": "81b9f4755c294c36bda8ac3b0d97a2b0",
          "orgId": "-100",
          "orgName": "平台组织机构",
          "deptName": "1112",
          "sortNo": 6
        }, {
          "deptId": "d975be1299a54940b3d672b1c7a7366d",
          "orgId": "-100",
          "orgName": "平台组织机构",
          "deptName": "11",
          "sortNo": 7
        }, {
          "deptId": "1d0bad9a61cc4409a8b6bcf97ced32b8",
          "orgId": "-100",
          "orgName": "平台组织机构",
          "deptName": "aaa",
          "sortNo": 8
        }]
      }
    }
  }
}

/* 组织管理 --- 列表数据 */
export function orgList () {
  return {
    url: '/sys/org/queryListByParentId',
    type: 'get',
    data: [{
      "orgId": "-100",
      "regId": "",
      "orgName": "平台组织机构",
      "orgShortName": "平台组织机构",
      "busObjType": 2047,
      "busObjs": "充电桩,配电,照明,插座,空调,锅炉,热泵,光伏,储能,给水,燃气",
      "parentId": "-1",
      "parentName": null,
      "sortNo": 1,
      "children": null,
      "leaf": true
    }, {
      "orgId": "3201030001",
      "regId": "320103",
      "orgName": "南京师范大学",
      "orgShortName": "南师大",
      "busObjType": 4,
      "busObjs": "插座",
      "parentId": "-1",
      "parentName": null,
      "sortNo": 2,
      "children": null,
      "leaf": true
    }]
  }
}