import isInteger from 'lodash/isInteger'


// 获取导航菜单列表 / 权限
export function nav() {
  return {
    // isOpen: false,
    url: '/sys/menu/nav',
    type: 'get',
    data: {
      "msg": "success",
      "menuList": [{
        "menuId": "1",
        "parentId": "-1",
        "parentName": null,
        "name": "首页",
        "url": "index",
        "perms": "",
        "type": 1,
        "icon": "icon-home",
        "orderNum": 1,
        "open": false,
        "list": null
      }, {
        "menuId": "2",
        "parentId": "-1",
        "parentName": null,
        "name": "设备监测",
        "url": null,
        "perms": "",
        "type": 0,
        "icon": "icon-display",
        "orderNum": 1,
        "open": false,
        "list": [{
          "menuId": "54",
          "parentId": "2",
          "parentName": null,
          "name": "能源监测",
          "url": null,
          "perms": "",
          "type": 0,
          "icon": "fa-user",
          "orderNum": 1,
          "open": false,
          "list": [{
            "menuId": "55",
            "parentId": "54",
            "parentName": null,
            "name": "电监测",
            "url": "equipment-monitor/energy-monitoring/electric-monitor",
            "perms": "",
            "type": 1,
            "icon": "fa-user",
            "orderNum": 1,
            "open": false,
            "list": null
          }, {
            "menuId": "56",
            "parentId": "54",
            "parentName": null,
            "name": "冷热监测",
            "url": "equipment-monitor/energy-monitoring/cold-hot-monitor",
            "perms": "",
            "type": 1,
            "icon": "fa-user",
            "orderNum": 2,
            "open": false,
            "list": null
          }]
        }, {
          "menuId": "3",
          "parentId": "2",
          "parentName": null,
          "name": "系统结构图",
          "url": "equipment-monitor/sys-pic",
          "perms": "",
          "type": 1,
          "icon": "fa-user",
          "orderNum": 2,
          "open": false,
          "list": null
        }, {
          "menuId": "4",
          "parentId": "2",
          "parentName": null,
          "name": "插座系统",
          "url": "equipment-monitor/socket",
          "perms": "",
          "type": 1,
          "icon": "fa-user-secret",
          "orderNum": 3,
          "open": false,
          "list": null
        }, {
          "menuId": "5",
          "parentId": "2",
          "parentName": null,
          "name": "高温相变储热",
          "url": "equipment-monitor/hths",
          "perms": "",
          "type": 1,
          "icon": "fa-file-image-o",
          "orderNum": 4,
          "open": false,
          "list": null
        }, {
          "menuId": "6",
          "parentId": "2",
          "parentName": null,
          "name": "光热发电",
          "url": "equipment-monitor/light-heat",
          "perms": "",
          "type": 1,
          "icon": "fa-file-text-o",
          "orderNum": 5,
          "open": false,
          "list": null
        }, {
          "menuId": "7",
          "parentId": "2",
          "parentName": null,
          "name": "压缩空气储能",
          "url": "equipment-monitor/compression-air",
          "perms": "",
          "type": 1,
          "icon": "fa-file-text-o",
          "orderNum": 6,
          "open": false,
          "list": null
        }, {
          "menuId": "8",
          "parentId": "2",
          "parentName": null,
          "name": "VRV空调",
          "url": "equipment-monitor/vrv",
          "perms": "",
          "type": 1,
          "icon": "fa-file-text-o",
          "orderNum": 7,
          "open": false,
          "list": null
        }, {
          "menuId": "9",
          "parentId": "2",
          "parentName": null,
          "name": "精密空调",
          "url": "equipment-monitor/precision",
          "perms": "",
          "type": 1,
          "icon": "fa-file-text-o",
          "orderNum": 8,
          "open": false,
          "list": null
        }, {
          "menuId": "10",
          "parentId": "2",
          "parentName": null,
          "name": "风机盘管",
          "url": "equipment-monitor/fan",
          "perms": "",
          "type": 1,
          "icon": "fa-file-text-o",
          "orderNum": 9,
          "open": false,
          "list": null
        }]
      }, {
        "menuId": "11",
        "parentId": "-1",
        "parentName": null,
        "name": "电网互动",
        "url": null,
        "perms": "",
        "type": 0,
        "icon": "icon-stats-dots",
        "orderNum": 2,
        "open": false,
        "list": [{
          "menuId": "12",
          "parentId": "11",
          "parentName": null,
          "name": "紧急需求响应",
          "url": "interactive/non-urgent",
          "perms": "",
          "type": 1,
          "icon": "fa-user",
          "orderNum": 1,
          "open": false,
          "list": null
        }, {
          "menuId": "13",
          "parentId": "11",
          "parentName": null,
          "name": "非紧急需求响应",
          "url": "interactive/urgent",
          "perms": "",
          "type": 1,
          "icon": "fa-user",
          "orderNum": 2,
          "open": false,
          "list": null
        }, {
          "menuId": "14",
          "parentId": "11",
          "parentName": null,
          "name": "操作历史",
          "url": "interactive/interactive-his",
          "perms": "",
          "type": 1,
          "icon": "fa-user",
          "orderNum": 3,
          "open": false,
          "list": null
        }]
      }, {
        "menuId": "15",
        "parentId": "-1",
        "parentName": null,
        "name": "统计分析",
        "url": null,
        "perms": "",
        "type": 0,
        "icon": "icon-pie-chart",
        "orderNum": 3,
        "open": false,
        "list": [{
          "menuId": "16",
          "parentId": "15",
          "parentName": null,
          "name": "用能分析",
          "url": "analysis/energy-analysis",
          "perms": "",
          "type": 1,
          "icon": "fa-user",
          "orderNum": 1,
          "open": false,
          "list": null
        }]
      }, {
        "menuId": "17",
        "parentId": "-1",
        "parentName": null,
        "name": "系统管理",
        "url": null,
        "perms": "",
        "type": 0,
        "icon": "icon-setting",
        "orderNum": 4,
        "open": false,
        "list": [{
          "menuId": "18",
          "parentId": "17",
          "parentName": null,
          "name": "权限管理",
          "url": null,
          "perms": "",
          "type": 0,
          "icon": "",
          "orderNum": 1,
          "open": false,
          "list": [{
            "menuId": "19",
            "parentId": "18",
            "parentName": null,
            "name": "资源管理",
            "url": "sys/sysresinfo",
            "perms": "",
            "type": 1,
            "icon": "fa-user",
            "orderNum": 1,
            "open": false,
            "list": null
          }, {
            "menuId": "20",
            "parentId": "18",
            "parentName": null,
            "name": "菜单管理",
            "url": "sys/sysmenu",
            "perms": "",
            "type": 1,
            "icon": "fa-user",
            "orderNum": 2,
            "open": false,
            "list": null
          }, {
            "menuId": "21",
            "parentId": "18",
            "parentName": null,
            "name": "用户管理",
            "url": "sys/user",
            "perms": "",
            "type": 1,
            "icon": "fa-user",
            "orderNum": 3,
            "open": false,
            "list": null
          }, {
            "menuId": "22",
            "parentId": "18",
            "parentName": null,
            "name": "角色管理",
            "url": "sys/sysroleinfo",
            "perms": "",
            "type": 1,
            "icon": "fa-user",
            "orderNum": 4,
            "open": false,
            "list": null
          }, {
            "menuId": "23",
            "parentId": "18",
            "parentName": null,
            "name": "部门管理",
            "url": "sys/sysdeptinfo",
            "perms": "",
            "type": 1,
            "icon": "fa-user",
            "orderNum": 5,
            "open": false,
            "list": null
          }, {
            "menuId": "24",
            "parentId": "18",
            "parentName": null,
            "name": "组织管理",
            "url": "sys/sysorg",
            "perms": "",
            "type": 1,
            "icon": "fa-user",
            "orderNum": 6,
            "open": false,
            "list": null
          }]
        }, {
          "menuId": "30",
          "parentId": "17",
          "parentName": null,
          "name": "数据管理",
          "url": null,
          "perms": "",
          "type": 0,
          "icon": "fa-user",
          "orderNum": 3,
          "open": false,
          "list": [{
            "menuId": "31",
            "parentId": "30",
            "parentName": null,
            "name": "能耗告警配置",
            "url": "management/manage-data/ecalarm",
            "perms": "",
            "type": 1,
            "icon": "fa-user",
            "orderNum": 1,
            "open": false,
            "list": null
          }, {
            "menuId": "32",
            "parentId": "30",
            "parentName": null,
            "name": "统计数据配置",
            "url": "management/manage-data/sc",
            "perms": "",
            "type": 1,
            "icon": "fa-user",
            "orderNum": 2,
            "open": false,
            "list": null
          }]
        }, {
          "menuId": "33",
          "parentId": "17",
          "parentName": null,
          "name": "设备管理",
          "url": null,
          "perms": "",
          "type": 0,
          "icon": "fa-user",
          "orderNum": 4,
          "open": false,
          "list": [{
            "menuId": "34",
            "parentId": "33",
            "parentName": null,
            "name": "设备信息配置",
            "url": "management/manage-device/device-info",
            "perms": "",
            "type": 1,
            "icon": "fa-user",
            "orderNum": 1,
            "open": false,
            "list": null
          }, {
            "menuId": "35",
            "parentId": "33",
            "parentName": null,
            "name": "设备详情",
            "url": "management/manage-device/device-detail",
            "perms": "",
            "type": 1,
            "icon": "fa-user",
            "orderNum": 2,
            "open": false,
            "list": null
          }, {
            "menuId": "36",
            "parentId": "33",
            "parentName": null,
            "name": "设备型号配置",
            "url": "management/manage-device/device-model",
            "perms": "",
            "type": 1,
            "icon": "fa-user",
            "orderNum": 3,
            "open": false,
            "list": null
          }, {
            "menuId": "37",
            "parentId": "33",
            "parentName": null,
            "name": "设备厂商配置",
            "url": "management/manage-device/device-firm",
            "perms": "",
            "type": 1,
            "icon": "fa-user",
            "orderNum": 4,
            "open": false,
            "list": null
          }, {
            "menuId": "38",
            "parentId": "33",
            "parentName": null,
            "name": "点位配置",
            "url": "management/manage-device/device-point",
            "perms": "",
            "type": 1,
            "icon": "fa-user",
            "orderNum": 5,
            "open": false,
            "list": null
          }, {
            "menuId": "39",
            "parentId": "33",
            "parentName": null,
            "name": "通讯设备",
            "url": "management/manage-comm/comm-device",
            "perms": "",
            "type": 1,
            "icon": "fa-user",
            "orderNum": 6,
            "open": false,
            "list": null
          }]
        }, {
          "menuId": "25",
          "parentId": "17",
          "parentName": null,
          "name": "站点管理",
          "url": null,
          "perms": "",
          "type": 0,
          "icon": "",
          "orderNum": 5,
          "open": false,
          "list": [{
            "menuId": "26",
            "parentId": "25",
            "parentName": null,
            "name": "站点管理",
            "url": "management/manage-site/site",
            "perms": "",
            "type": 1,
            "icon": "fa-user",
            "orderNum": 1,
            "open": false,
            "list": null
          }, {
            "menuId": "27",
            "parentId": "25",
            "parentName": null,
            "name": "楼层管理",
            "url": "management/manage-site/floor",
            "perms": "",
            "type": 1,
            "icon": "fa-user",
            "orderNum": 2,
            "open": false,
            "list": null
          }, {
            "menuId": "28",
            "parentId": "25",
            "parentName": null,
            "name": "费用管理",
            "url": "management/manage-site/cost",
            "perms": "",
            "type": 1,
            "icon": "fa-user",
            "orderNum": 3,
            "open": false,
            "list": null
          }, {
            "menuId": "29",
            "parentId": "25",
            "parentName": null,
            "name": "字典管理",
            "url": "management/manage-site/dictionary",
            "perms": "",
            "type": 1,
            "icon": "fa-user",
            "orderNum": 4,
            "open": false,
            "list": null
          }]
        }, {
          "menuId": "40",
          "parentId": "17",
          "parentName": null,
          "name": "通讯管理",
          "url": null,
          "perms": "",
          "type": 0,
          "icon": "fa-user",
          "orderNum": 5,
          "open": false,
          "list": [{
            "menuId": "41",
            "parentId": "40",
            "parentName": null,
            "name": "通讯连接",
            "url": "management/manage-comm/comm-connect",
            "perms": "",
            "type": 1,
            "icon": "fa-user",
            "orderNum": 1,
            "open": false,
            "list": null
          }, {
            "menuId": "42",
            "parentId": "40",
            "parentName": null,
            "name": "通讯协议104",
            "url": "management/manage-comm/comm-agreement",
            "perms": "",
            "type": 1,
            "icon": "fa-user",
            "orderNum": 2,
            "open": false,
            "list": null
          }, {
            "menuId": "43",
            "parentId": "40",
            "parentName": null,
            "name": "通讯协议104副",
            "url": "management/manage-comm/comm-agreement-sub",
            "perms": "",
            "type": 1,
            "icon": "fa-user",
            "orderNum": 3,
            "open": false,
            "list": null
          }, {
            "menuId": "44",
            "parentId": "40",
            "parentName": null,
            "name": "redis主",
            "url": "management/manage-comm/comm-redis",
            "perms": "",
            "type": 1,
            "icon": "fa-user",
            "orderNum": 4,
            "open": false,
            "list": null
          }, {
            "menuId": "45",
            "parentId": "40",
            "parentName": null,
            "name": "redis副",
            "url": "management/manage-comm/comm-redis-sub",
            "perms": "",
            "type": 1,
            "icon": "fa-user",
            "orderNum": 5,
            "open": false,
            "list": null
          }, {
            "menuId": "46",
            "parentId": "40",
            "parentName": null,
            "name": "遥测",
            "url": "management/remote/tycrule",
            "perms": "",
            "type": 1,
            "icon": "fa-user",
            "orderNum": 6,
            "open": false,
            "list": null
          }, {
            "menuId": "47",
            "parentId": "40",
            "parentName": null,
            "name": "遥控",
            "url": "management/remote/tykrule",
            "perms": "",
            "type": 1,
            "icon": "fa-user",
            "orderNum": 7,
            "open": false,
            "list": null
          }, {
            "menuId": "48",
            "parentId": "40",
            "parentName": null,
            "name": "遥脉",
            "url": "management/remote/tymrule",
            "perms": "",
            "type": 1,
            "icon": "fa-user",
            "orderNum": 8,
            "open": false,
            "list": null
          }, {
            "menuId": "49",
            "parentId": "40",
            "parentName": null,
            "name": "遥调",
            "url": "management/remote/tytrule",
            "perms": "",
            "type": 1,
            "icon": "fa-user",
            "orderNum": 9,
            "open": false,
            "list": null
          }, {
            "menuId": "50",
            "parentId": "40",
            "parentName": null,
            "name": "遥信",
            "url": "management/remote/tyxrule",
            "perms": "",
            "type": 1,
            "icon": "fa-user",
            "orderNum": 10,
            "open": false,
            "list": null
          }]
        }]
      }, {
        "menuId": "51",
        "parentId": "-1",
        "parentName": null,
        "name": "告警统计",
        "url": null,
        "perms": "",
        "type": 0,
        "icon": "icon-pie-chart",
        "orderNum": 6,
        "open": false,
        "list": [{
          "menuId": "52",
          "parentId": "51",
          "parentName": null,
          "name": "能耗告警",
          "url": "alarm-statistics/energy-alarm",
          "perms": "",
          "type": 1,
          "icon": "fa-user",
          "orderNum": 1,
          "open": false,
          "list": null
        }, {
          "menuId": "53",
          "parentId": "51",
          "parentName": null,
          "name": "统计数据",
          "url": "alarm-statistics/statistics",
          "perms": "",
          "type": 1,
          "icon": "fa-user",
          "orderNum": 2,
          "open": false,
          "list": null
        }]
      }],
      "code": 0,
      "permissions": ["1000:4", "1040:8", "1000:8", "1040:1", "1040:16", "1040:2", "1000:64", "1000:1", "1000:2", "1000:32", "1040:4", "1000:128", "1000:1024", "1000:256", "1000:16", "1000:512", "1000:111"]
    }
  }
}


// 获取菜单列表
export function list() {
  return {
    isOpen: false,
    url: '/sys/menu/list',
    type: 'get',
    data: [{
        'menuId': 1,
        'parentId': 0,
        'parentName': null,
        'name': '系统管理',
        'url': null,
        'perms': null,
        'type': 0,
        'icon': 'fa fa-cog',
        'orderNum': 0,
        'open': null,
        'list': null
      },
      {
        'menuId': 2,
        'parentId': 1,
        'parentName': '系统管理',
        'name': '管理员列表',
        'url': 'modules/sys/user.html',
        'perms': null,
        'type': 1,
        'icon': 'fa fa-user',
        'orderNum': 1,
        'open': null,
        'list': null
      },
      {
        'menuId': 3,
        'parentId': 1,
        'parentName': '系统管理',
        'name': '角色管理',
        'url': 'modules/sys/role.html',
        'perms': null,
        'type': 1,
        'icon': 'fa fa-user-secret',
        'orderNum': 2,
        'open': null,
        'list': null
      },
      {
        'menuId': 4,
        'parentId': 1,
        'parentName': '系统管理',
        'name': '菜单管理',
        'url': 'modules/sys/menu.html',
        'perms': null,
        'type': 1,
        'icon': 'fa fa-th-list',
        'orderNum': 3,
        'open': null,
        'list': null
      },
      {
        'menuId': 5,
        'parentId': 1,
        'parentName': '系统管理',
        'name': 'SQL监控',
        'url': 'druid/sql.html',
        'perms': null,
        'type': 1,
        'icon': 'fa fa-bug',
        'orderNum': 4,
        'open': null,
        'list': null
      },
      {
        'menuId': 6,
        'parentId': 1,
        'parentName': '系统管理',
        'name': '定时任务',
        'url': 'modules/job/schedule.html',
        'perms': null,
        'type': 1,
        'icon': 'fa fa-tasks',
        'orderNum': 5,
        'open': null,
        'list': null
      },
      {
        'menuId': 7,
        'parentId': 6,
        'parentName': '定时任务',
        'name': '查看',
        'url': null,
        'perms': 'sys:schedule:list,sys:schedule:info',
        'type': 2,
        'icon': null,
        'orderNum': 0,
        'open': null,
        'list': null
      },
      {
        'menuId': 8,
        'parentId': 6,
        'parentName': '定时任务',
        'name': '新增',
        'url': null,
        'perms': 'sys:schedule:save',
        'type': 2,
        'icon': null,
        'orderNum': 0,
        'open': null,
        'list': null
      },
      {
        'menuId': 9,
        'parentId': 6,
        'parentName': '定时任务',
        'name': '修改',
        'url': null,
        'perms': 'sys:schedule:update',
        'type': 2,
        'icon': null,
        'orderNum': 0,
        'open': null,
        'list': null
      },
      {
        'menuId': 10,
        'parentId': 6,
        'parentName': '定时任务',
        'name': '删除',
        'url': null,
        'perms': 'sys:schedule:delete',
        'type': 2,
        'icon': null,
        'orderNum': 0,
        'open': null,
        'list': null
      },
      {
        'menuId': 11,
        'parentId': 6,
        'parentName': '定时任务',
        'name': '暂停',
        'url': null,
        'perms': 'sys:schedule:pause',
        'type': 2,
        'icon': null,
        'orderNum': 0,
        'open': null,
        'list': null
      },
      {
        'menuId': 12,
        'parentId': 6,
        'parentName': '定时任务',
        'name': '恢复',
        'url': null,
        'perms': 'sys:schedule:resume',
        'type': 2,
        'icon': null,
        'orderNum': 0,
        'open': null,
        'list': null
      },
      {
        'menuId': 13,
        'parentId': 6,
        'parentName': '定时任务',
        'name': '立即执行',
        'url': null,
        'perms': 'sys:schedule:run',
        'type': 2,
        'icon': null,
        'orderNum': 0,
        'open': null,
        'list': null
      },
      {
        'menuId': 14,
        'parentId': 6,
        'parentName': '定时任务',
        'name': '日志列表',
        'url': null,
        'perms': 'sys:schedule:log',
        'type': 2,
        'icon': null,
        'orderNum': 0,
        'open': null,
        'list': null
      },
      {
        'menuId': 15,
        'parentId': 2,
        'parentName': '管理员列表',
        'name': '查看',
        'url': null,
        'perms': 'sys:user:list,sys:user:info',
        'type': 2,
        'icon': null,
        'orderNum': 0,
        'open': null,
        'list': null
      },
      {
        'menuId': 16,
        'parentId': 2,
        'parentName': '管理员列表',
        'name': '新增',
        'url': null,
        'perms': 'sys:user:save,sys:role:select',
        'type': 2,
        'icon': null,
        'orderNum': 0,
        'open': null,
        'list': null
      },
      {
        'menuId': 17,
        'parentId': 2,
        'parentName': '管理员列表',
        'name': '修改',
        'url': null,
        'perms': 'sys:user:update,sys:role:select',
        'type': 2,
        'icon': null,
        'orderNum': 0,
        'open': null,
        'list': null
      },
      {
        'menuId': 18,
        'parentId': 2,
        'parentName': '管理员列表',
        'name': '删除',
        'url': null,
        'perms': 'sys:user:delete',
        'type': 2,
        'icon': null,
        'orderNum': 0,
        'open': null,
        'list': null
      },
      {
        'menuId': 19,
        'parentId': 3,
        'parentName': '角色管理',
        'name': '查看',
        'url': null,
        'perms': 'sys:role:list,sys:role:info',
        'type': 2,
        'icon': null,
        'orderNum': 0,
        'open': null,
        'list': null
      },
      {
        'menuId': 20,
        'parentId': 3,
        'parentName': '角色管理',
        'name': '新增',
        'url': null,
        'perms': 'sys:role:save,sys:menu:list',
        'type': 2,
        'icon': null,
        'orderNum': 0,
        'open': null,
        'list': null
      },
      {
        'menuId': 21,
        'parentId': 3,
        'parentName': '角色管理',
        'name': '修改',
        'url': null,
        'perms': 'sys:role:update,sys:menu:list',
        'type': 2,
        'icon': null,
        'orderNum': 0,
        'open': null,
        'list': null
      },
      {
        'menuId': 22,
        'parentId': 3,
        'parentName': '角色管理',
        'name': '删除',
        'url': null,
        'perms': 'sys:role:delete',
        'type': 2,
        'icon': null,
        'orderNum': 0,
        'open': null,
        'list': null
      },
      {
        'menuId': 23,
        'parentId': 4,
        'parentName': '菜单管理',
        'name': '查看',
        'url': null,
        'perms': 'sys:menu:list,sys:menu:info',
        'type': 2,
        'icon': null,
        'orderNum': 0,
        'open': null,
        'list': null
      },
      {
        'menuId': 24,
        'parentId': 4,
        'parentName': '菜单管理',
        'name': '新增',
        'url': null,
        'perms': 'sys:menu:save,sys:menu:select',
        'type': 2,
        'icon': null,
        'orderNum': 0,
        'open': null,
        'list': null
      },
      {
        'menuId': 25,
        'parentId': 4,
        'parentName': '菜单管理',
        'name': '修改',
        'url': null,
        'perms': 'sys:menu:update,sys:menu:select',
        'type': 2,
        'icon': null,
        'orderNum': 0,
        'open': null,
        'list': null
      },
      {
        'menuId': 26,
        'parentId': 4,
        'parentName': '菜单管理',
        'name': '删除',
        'url': null,
        'perms': 'sys:menu:delete',
        'type': 2,
        'icon': null,
        'orderNum': 0,
        'open': null,
        'list': null
      },
      {
        'menuId': 27,
        'parentId': 1,
        'parentName': '系统管理',
        'name': '参数管理',
        'url': 'modules/sys/config.html',
        'perms': 'sys:config:list,sys:config:info,sys:config:save,sys:config:update,sys:config:delete',
        'type': 1,
        'icon': 'fa fa-sun-o',
        'orderNum': 6,
        'open': null,
        'list': null
      },
      {
        'menuId': 29,
        'parentId': 1,
        'parentName': '系统管理',
        'name': '系统日志',
        'url': 'modules/sys/log.html',
        'perms': 'sys:log:list',
        'type': 1,
        'icon': 'fa fa-file-text-o',
        'orderNum': 7,
        'open': null,
        'list': null
      },
      {
        'menuId': 30,
        'parentId': 1,
        'parentName': '系统管理',
        'name': '文件上传',
        'url': 'modules/oss/oss.html',
        'perms': 'sys:oss:all',
        'type': 1,
        'icon': 'fa fa-file-image-o',
        'orderNum': 6,
        'open': null,
        'list': null
      },
      {
        'menuId': 31,
        'parentId': 0,
        'parentName': null,
        'name': 'test',
        'url': null,
        'perms': null,
        'type': 0,
        'icon': null,
        'orderNum': 5,
        'open': null,
        'list': null
      },
      {
        'menuId': 46,
        'parentId': 2,
        'parentName': '管理员列表',
        'name': 'test',
        'url': null,
        'perms': null,
        'type': 2,
        'icon': null,
        'orderNum': 0,
        'open': null,
        'list': null
      },
      {
        'menuId': 47,
        'parentId': 1,
        'parentName': '系统管理',
        'name': 'test2',
        'url': '/test/test2.html',
        'perms': null,
        'type': 1,
        'icon': null,
        'orderNum': 0,
        'open': null,
        'list': null
      }
    ]
  }
}

// 获取上级菜单
export function select() {
  return {
    isOpen: false,
    url: '/sys/menu/select',
    type: 'get',
    data: {}
  }
}

// 获取菜单信息
export function info(id) {
  return {
    isOpen: false,
    url: '/sys/menu/info' + (isInteger(id) ? `/${id}` : ''),
    type: 'get',
    data: {}
  }
}

// 添加菜单
export function add(params) {
  return {
    isOpen: false,
    url: '/sys/menu/save',
    type: 'post',
    data: {}
  }
}

// 修改菜单
export function update(params) {
  return {
    isOpen: false,
    url: '/sys/menu/update',
    type: 'post',
    data: {}
  }
}

// 删除菜单
export function del(id) {
  return {
    isOpen: false,
    url: '/sys/menu/delete' + (isInteger(id) ? `/${id}` : ''),
    type: 'post',
    data: {}
  }
}
